routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');
Route::get('/tambak', 'HomeController@farms');
Route::post('/tambak', 'HomeController@search');
Route::get('/atur-suhu', 'HomeController@setTemp');
Route::patch('/atur-suhu/{parameter}', 'HomeController@updateTemp');
Route::get('/riwayat', 'HomeController@history')->name('history');
Route::post('/riwayat/export', 'HomeController@export');
Route::post('/riwayat/import', 'HomeController@import');
Route::get('/riwayat/{farmHistory}', 'HomeController@detailHistory')->name('detail.history');

// Route::get('/', 'HomeController@index');

// // Route Admin
// Route::get('/admin', 'AdminController@index')->name('admin');
// Route::post('/admin/export', 'AdminController@export')->name('admin.export');
// Route::get('/admin/user-management', 'AdminController@management')->name('management');
// Route::get('/admin/user-management/edit/{user}', 'AdminController@edit');
// Route::patch('/admin/user-management/{user}', 'AdminController@update');
// Route::delete('/admin/user-management/{user}', 'AdminController@destroy');
// Route::get('/admin/list-job','AdminController@listJob')->name('list-job');
// Route::post('/admin/list-job/create','AdminController@createJob')->name('create.job');
// Route::delete('/admin/list-job/{listJob}', 'AdminController@destroyJob');
// Route::get('/admin/list-job/edit/{listJob}', 'AdminController@editJob')->name('edit.job');
// Route::patch('/admin/list-job/{listJob}', 'AdminController@updateJob')->name('update.job');

// Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
//     return view('dashboard');
// })->name('dashboard');

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <x-jet-welcome />
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/detailHistory.blade.php
@extends('layouts.app')
@section('content')
        <!-- Static Table Start -->
        <div class="data-table-area mg-b-15">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="sparkline13-list">
                            <div class="sparkline13-hd">
                                <form action="/riwayat/export" method="POST">
                                    @csrf
                                    <input type="hidden" value="{{$farm->id}}" name="farm_id">
                                <div class="main-sparkline13-hd">
                                    <h1>Riwayat Tambak {{$farm->name}}</h1>
                                    <button type="submit" class="btn btn-primary">Export</button>
                                </div>
                            </div>
                            <div class="sparkline13-graph">
                                <div class="datatable-dashv1-list custom-datatable-overright">
                                    <div id="toolbar">
                                        <div class="white-box analytics-info-cs">
                                            {{-- <h3 class="box-title">Cari Tambak</h3> --}}
                                        <div class="sparkline10-graph">
                                            <div class="input-knob-dial-wrap">
                                                <div class="row">
                                                     
                                                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                                                <div class="mg-b-20">
                                                                    <label>Tanggal Awal</label>
                                                                    <input type="date" class="form-control" id="startDate" name="startDate"/>
                                                                </div>
                                                            </div>
                                                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                                                <div class=" mg-b-20">
                                                                    <label>Tanggal Akhir</label>
                                                                    <input type="date" class="form-control" id="endDate" name="endDate"/>
                                                                </div>
                                                            </div>
                                                        </form>
                                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                                <div class=" mg-b-20">
                                                                    <button class="btn btn-primary" id="dateButton">Search</button>
                                                                </div>
                                                            </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <table id="table-history" class="table table-striped">
                                        <thead>
                                            <tr>
                                                <th class="sorting" data-field="name" data-editable="true">tanggal</th>
                                                <th class="sorting" data-field="name" data-editable="true">jam</th>
                                                <th class="sorting" data-field="name" data-editable="true">ph</th>
                                                <th class="sorting" data-field="name" data-editable="true">temperatur</th>
                                                <th class="sorting" data-field="name" data-editable="true">do</th>
                                            </tr>
                                        </thead>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Static Table End -->
@endsection


@section('script')

<script>

    $.ajaxSetup({
        headers: {
                "X-CSRF-TOKEN": $("meta[name='csrf-token']").attr("content"),
            }
        })

</script>

<script>

$(document).ready(function(){
    var historyTable =  $('#table-history').DataTable({
    processing: true,
    serverSide: true,
    destroy: true,
    responsive: true,
    ajax: {
        type: "GET",
        url: "/riwayat/{{$farm->id}}",
        data: {tanggal1 : "{{$tanggal1}}", tanggal2 : "{{$tanggal2}}"},

    },
    columns: [
        { data: 'date', name: 'date'},
        { data: 'time', name: 'time'},
        { data: 'ph', name: 'ph'},
        { data: 'temp', name: 'temp'},
        { data: 'do', name: 'do'},
    ],
    });
    $('#dateButton').click(function() {
        var tanggal1 = $('#startDate').val();
        var tanggal2 = $('#endDate').val();

        historyTable.destroy()



        historyTable = $('#table-history').DataTable({
        processing: true,
        serverSide: true,
        destroy: true,
        responsive: true,
        ajax: {
            type: "GET",
            url: "/riwayat/{{$farm->id}}",
            data: {
                data1:tanggal1,
                data2:tanggal2,
            },
        },
        columns: [
            { data: 'date', name: 'date'},
            { data: 'time', name: 'time'},
            { data: 'ph', name: 'ph'},
            { data: 'temp', name: 'temp'},
            { data: 'do', name: 'do'},
        ],
        });
    });
});


</script>

@endsection

resources/views/farmSite.blade.php
@extends('layouts.app')
@section('content')


    {{-- statistik atas --}}
    <div class="traffice-source-area mg-b-30">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="white-box analytics-info-cs">
                        <h3 class="box-title">Cari Tambak</h3>
                        <form action="/tambak/" method="POST">
                            @csrf
                            <div class="sparkline10-graph">
                                <div class="input-knob-dial-wrap">
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="chosen-select-single mg-b-20">
                                                <label>Lokasi</label>
                                                <select data-placeholder="Choose a Country..." class="chosen-select" tabindex="-1" name="location">
                                                    @foreach ($locations as $location)
                                                        <option value="{{$location->name}}">{{$location->name}}</option>
                                                    @endforeach
                                                </select>
                                            </div>
                                            <div class=" mg-b-20">
                                                <label>Tambak</label>
                                                <input type="text" class="form-control" placeholder="Masukkan Tambak" name="tambak"/>
                                            </div>
                                            <div class=" mg-b-20">
                                                <button type="submit" class="btn btn-primary">Search</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@if ($searchCheck != NULL)
    {{-- statistik ph --}}
    <div class="product-sales-area mg-tb-30">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="sparkline-list">
                        <div class="smart-sparkline-hd">
                            <div class="smart-main-spark-hd">
                                <h1>PH TAMBAK {{$farmName}}</h1>
                            </div>
                        </div>
                        <div class="smart-sparkline-list">
                            @if($farms->count() > 0)
                            <div id="phChart"></div>
                            @else
                            <div>Tidak Ada Data Hari Ini</div>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {{-- statistik suhu --}}
    <div class="product-sales-area mg-tb-30">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="sparkline-list">
                        <div class="smart-sparkline-hd">
                            <div class="smart-main-spark-hd">
                                <h1>SUHU TAMBAK {{$farmName}}</h1>
                            </div>
                        </div>
                        <div class="smart-sparkline-list">
                            @if($farms->count() > 0)
                            <div id="suhuChart"></div>
                            @else
                            <div>Tidak Ada Data Hari Ini</div>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {{-- statistik oksigen --}}
    <div class="product-sales-area mg-tb-30">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="sparkline-list">
                        <div class="smart-sparkline-hd">
                            <div class="smart-main-spark-hd">
                                <h1>DO TAMBAK {{$farmName}}</h1>
                            </div>
                        </div>
                        <div class="smart-sparkline-list">
                            @if($farms->count() > 0)
                            <div id="doChart"></div>
                            @else
                            <div>Tidak Ada Data Hari Ini</div>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@else
    <div class="product-sales-area mg-tb-30">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="sparkline-list">
                        <div class="smart-sparkline-hd">
                            <div class="smart-main-spark-hd">
                                <h1>Silahkan memasukkan lokasi dan tambak yang diinginkan</h1>
                            </div>
                        </div>
                        <div class="smart-sparkline-list">
                            {{-- <div>Tidak Ada Data Hari Ini</div> --}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endif

@endsection

@section('script')

<script>
   google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(phChart);
      google.charts.setOnLoadCallback(suhuChart);
      google.charts.setOnLoadCallback(doChart);

    function phChart() {

        var ph = google.visualization.arrayToDataTable([
            ['hours', 'ph', {role: 'style'}],
            @foreach ($farms as $farm)
            ['{{$farm->time}}', {{$farm->ph}},
            @if($farm->ph >= $ph->minimum && $farm->ph <= $ph->maximum)
            'blue'
            @else
            'red'
            @endif
            ],
            @endforeach
        ]);

        var options = {
          title: 'PH',
          curveType: 'function',
          legend: { position: 'bottom' }
        };

      var chart = new google.visualization.LineChart(document.getElementById('phChart'));

      chart.draw(ph, options);
    }

    function suhuChart() {
        var suhu = google.visualization.arrayToDataTable([
            ['hours', 'suhu', {role: 'style'}],
            @foreach ($farms as $farm)
            ['{{$farm->time}}', {{$farm->temp}},
            @if($farm->temp >= $temp->minimum && $farm->temp <= $temp->maximum)
            'blue'
            @else
            'red'
            @endif
            ],
            @endforeach
        ]);

        var options = {
          title: 'SUHU',
          curveType: 'function',
          legend: { position: 'bottom' }
        };

      var chart = new google.visualization.LineChart(document.getElementById('suhuChart'));

      chart.draw(suhu, options);
    }

    function doChart() {
        var oxygen = google.visualization.arrayToDataTable([
            ['hours', 'dissolved oxygen', { role: 'style'}],
            @foreach ($farms as $farm)
            ['{{$farm->time}}', {{$farm->do}}, 
                @if($farm->do >= $do->minimum && $farm->do <= $do->maximum)
                'blue'
                @else
                'red'
                @endif
            ],
            @endforeach
        ]);

        var options = {
          title: 'Dissolved Oxygen',
          curveType: 'function',
          legend: { position: 'bottom' }
        };

      var chart = new google.visualization.LineChart(document.getElementById('doChart'));

      chart.draw(oxygen, options);
    }

</script>

@endsection

resources/views/history.blade.php
@extends('layouts.app')
@section('content')
        <!-- Static Table Start -->
        <div class="data-table-area mg-b-15">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="sparkline13-list">
                            <div class="sparkline13-hd">
                                <div class="main-sparkline13-hd">
                                    <h1>Tabel Tambak</h1>
                                </div>
                            </div>
                            <!-- Multi Upload Start-->
                            {{-- <div class="multi-uploaded-area mg-b-15">
                                <div class="container-fluid">
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="dropzone-pro mg-tb-30">
                                                <div id="dropzone1" class="multi-uploader-cs">
                                                    <form action="/riwayat/import" class="dropzone dropzone-custom needsclick" id="demo1-upload" method="post" enctype="multipart/form-data">
                                                        @csrf
                                                        <div class="dz-message needsclick download-custom">
                                                            <i class="fa fa-download" aria-hidden="true"></i>
                                                            <h2>Drop files here or click to upload.</h2>
                                                            <p><span class="note needsclick">(This is just a demo dropzone. Selected files are <strong>not</strong> actually uploaded.)</span>
                                                            </p>
                                                        </div>
                                                    </div>
                                                    <button type="submit" class="btn btn-primary">IMPORT</button>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> --}}
                            <!-- Multi Upload End-->
                            <form action="/riwayat/import" method="post" enctype="multipart/form-data">
                                @csrf
                                <div class="row">
                                    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                                        <input name="excel" class="form-control" type="file" required>
                                    </div>
                                    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                                        <button class="btn btn-primary">Import</button>
                                    </div>
                                </div>
                            </form>
                            <div class="sparkline13-graph">
                                <div class="datatable-dashv1-list custom-datatable-overright">
                                    <table id="table-history" class="table table-striped table-bordered">
                                        <thead>
                                            <tr>
                                                <th class="sorting" data-field="name" data-editable="true">Lokasi</th>
                                                <th class="sorting" data-field="name" data-editable="true">Tambak</th>
                                                <th class="sorting" data-field="email" data-editable="true">Detail</th>
                                            </tr>
                                        </thead>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Static Table End -->
@endsection


@section('script')

<script>

    $.ajaxSetup({
        headers: {
                "X-CSRF-TOKEN": $("meta[name='csrf-token']").attr("content"),
            }
        })

</script>

<script>

$(document).ready(function(){
    var historyTable =  $('#table-history').DataTable({
    processing: true,
    serverSide: true,
    destroy: true,
    responsive: true,
    ajax: {
        type: "GET",
        url: "{{route('history')}}",
    },
    columns: [
        { data: 'location', name: 'location'},
        { data: 'name', name: 'name'},
        { data: 'action', name: 'action'},
    ],
    });
});

</script>

@endsection

resources/views/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $policy !!}
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/setTemp.blade.php
@extends('layouts.app')
@section('content')


        {{-- statistik atas --}}
        <div class="traffice-source-area mg-b-30">
            <div class="container-fluid">
                <div class="row">
                    @foreach ($params as $param)
                    <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
                        <div class="white-box analytics-info-cs">
                            <h3 class="box-title">Pengaturan {{$param->name}}</h3>
                            <form action="/atur-suhu/{{$param->id}}" method="POST">
                                @method('patch')
                                @csrf
                                <ul class="list-inline two-part-sp">
                                    <li>Minimum</li>
                                    <li class="text-right sp-cn-r">
                                        <div class="form-select-list">
                                            <input type="text" class="form-control" name="minimum" value={{$param->minimum}}>
                                        </div>
                                    </li>
                                    <li></li>
                                    <li></li>
                                    <li>Maximum</li>
                                    <li class="text-right graph-four-ctn">
                                        <div class="form-select-list">
                                            <input type="text" class="form-control" name="maximum" value="{{$param->maximum}}">
                                        </div>
                                    </li>
                                    <div style="float: right; margin-top: 20px; margin-right: 10px">
                                        <button class=" btn btn-sm btn-primary">Simpan</button>
                                    </div>
                                </ul>
                            </form>
                        </div>
                    </div>
                    @endforeach
                </div>
            </div>
        </div>
@endsection

resources/views/terms.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $terms !!}
            </div>
        </div>
    </div>
</x-guest-layout>